### ISSUE TITLE
1章 「DDDへの誘い」

### ISSUE THREAD

**Issue by hiromoon** [hiromoon/ReadingDDD#1]

**Comment by Shusaku-Sahashi** [comment]
ユビキタス言語を使用すれば、ドメインエキスパート（銀行系ならエンドユーザ、システム部署がなりそう）もソース内容をある程度理解できることは素晴らしいことだと考えるし、そうあってほしいと思う。

ただ、ユビキタス言語を共に考えることもそうだが、少なくとも英語で的確な単語をある程度知っている必要があるので、教育こすとがかなり高いのも分かった。

**Comment by shirosuke** [comment]
dddを導入するところまでもっていくのにかなり時間がかかりそうだなと思った。ドメインエキスパート、マネージャ、他の開発者を巻き込んでユビキタス言語を作って
いくのが大変そう。

新しい文化を受け入れるとか、皆で勉強するとかできんとキツいかもね。
