### ISSUE TITLE
8 章 ドメインイベント

### ISSUE THREAD

**Issue by hiromoon** [hiromoon/ReadingDDD#11]
## 8.1
* ドメインイベントのパターンはエヴァンズ本の後発
* ドメインイベント: 「ドメインエキスパートが気にかける、何かの出来事」
* ドメイン内の誰かが通知して欲しがっていることを、イベントとしてモデリングする
* イベントを送る場合には結果整合性を利用する
  - 二相コミットや集約のルールから関心を切り離すため

## 8.2
* イベントの名前やプロパティには、イベント発生元コンテキストのユビキタス言語を利用する
  - 実行コマンド: BacklogItem#commitTo(Sprint aSprint)
  - 発行されるイベント: BacklogItemCommitted
  - IDDD 8.2章の例より
* イベントは一般的には不変クラスとして設計される
* サブスクライバに付加情報を与えることもできる
  - プロパティを追加する
  - 操作を追加する
* サブスクライバが集約に追加の問い合わせをするのは、設計を複雑化させるので避ける
* イベントに追加する振る舞いは副作用のないものにする

* ユーザのアクションをイベントとして表現する場合には、イベントを集約としてモデリングする
  - イベントは不変なクラスとしてモデリングする
  - イベントには一意な識別子をあたえるとよい
    - サブスクライバが重複して配送されてきたメッセージを無視するため
* イベントをリポジトリに追加すると同時に、メッセージ基盤を使って出版できる
  - イベントの整合性を保つために、共通のデータソースに保存もしくは2相コミットをする必要がある

## 8.3
* インフラにドメインモデルの情報を漏らしたくない
  - オブザーバパターンを利用することで回避する

### パブリッシャー
* 集約がサブスクライバに通知を送れるようにサービスを提供する

### サブスクライバ
* イベントを発行する集約と同一スレッド上で実行される任意のコンポーネント
* イベントが発行される前に限って、イベントを購読することができる
* __単一のトランザクション内では単一の集約だけを変更する__

## 8.4
* リモートの境界づけられたコンテキストへのイベントの送付
  - メッセージ・キューやRESTなどをつかう
  - 結果整合性を導入する必要があ
  - 下記の2つは整合性を保つ必要がある
    + ドメインモデルの永続化ストア
    + イベントをメッセージング基盤が転送する際につかう永続化ストア
  - モデルへの変更が永続化された時にイベントが配送されることが保証される
### モデルとイベントの整合性を保ちつつ永続化する方法
||メリット|デメリット|
|:--|:--|:--|
|1.  永続化ストアを共有する|パフォーマンス○、変更とメッセージの追加を同一のトランザクションで行える|メッセージングシステムのストレージ領域を、モデルと同じデータベースに配置する必要がある|
|2. XAトランザクション(二相コミット)で制御する| モデルとメッセージングのストレージを別にできる| グローバルなトランザクションを考慮しなければならない|
|3. イベントストアを用意する(後述)|単一のローカルトランザクション内で整合性が保証される|イベントをメカニズム経由で送信する必要がある、クライアントサイドで重複排除をする必要がある|

### 自立型のサービス・システム
* 他のシステムに依存せずに動くシステム・アプリ
  - RPCを避けることで独立性が達成できる
  - RPCを使うとAPIリクエストの完了を待つ必要があるため☓

### 遅延の許容
* 数分〜数時間程度の遅延は受け入れられる事が多い
* 遅延と一貫性はトレードオフがある
* どちらを優先させるかはシステム要件次第

##### イベントストアを使ってできること
1. ドメインイベントを発行する際のキューとして使う
2. RESTベースのイベント通知ができる(1とほぼ同じ)
3. モデル上で実行されたすべてのコマンドの結果を履歴として記録する
4. データを使って、傾向の分析や今後の予測ができる(?)
5. イベントを元に集約のインスタンスを再構築できる
6. 過去のある時点以降の変更を取り消すことができる

#### RESTful
* PubSubの基本を守ることが前提
  * キューとして使おうとすると破綻する
* Pullモデルの要求としてならうまく機能する
* 複数のプロデューサが送る通知の順序が重要になる場合には向いてない
  * MQを使いましょう
  * ポーリング方式はキューとして使うには向いてない

#### メッセージングミドルウェア
* RabbitMQ他
* PubSubとキューのどちらにも対応できる
* Pushモデルでサブスクライバへイベントを通知する
* メッセージングシステムは、送信義務だけを負い、受信の確認はしない
#### イベントの重複
* サブスクライバの処理で冪等性を担保する
* サブスクライバ側で重複してイベントを受信した場合には無視する作りにする

**Comment by shirosuke** [comment]
@hiromoon  まとめどうも〜。結構ボリューミーな章だったから読むの大変だったわ。。

## 8.1
> * ドメインイベントのパターンはエヴァンズ本の後発

@Shusaku-Sahashi  には言ってなかったかもだけど、IDDDを先に読むように提案した理由の一つはこれ。ドメインイベントも含めて、後発だけど重要な概念を先にやっておきたかったから。

## 8.2
P.70のコラボレーションコンテキストの図みたいに、ドメインイベントも含めてドメインモデリングしておくと、業務視点のイベントちゃんと作れそう。

## 8.4
> トランザクションの具体的な実装と使い分けの話がよくわからなかった
> * XAトランザクションの実装(複数のミドルウェアでトランザクション？)
> * グローバルトランザクション
> * ローカルトランザクション

使い分けは、やっぱり非機能の要件とその非機能要件を満たすためのメッセージングMWの制約によるのかなーと（メッセージングミドルウェア使ったことないからピンときてないけど。。）。
個人的には、複雑で分散DBやメッセージングMWの知見がかなり必要なそうな②は避けたいところ。

具体的な実装パターンについては、パターン本参照して見ると良いらしいよ（俺は読んでないけど）。
* Enterprise Integration Patterns
* Reactive Messaging Pattern

**Comment by Shusaku-Sahashi** [comment]
# 第８章：ドメインイベント
DDDのドメインイベントに関してです。
そもそもイベントという用語さえ理解できていませんでした。。( ;∀;)

全容をざっと理解できるようにできればいいかなと思います。

ドメインイベントとは、ドメイン内で発生したイベントを知らせるための機能です。
PublisherとSubcriberの２つのアクターの間でイベントを購読するという構造で実現されます。

## ドメインのモデリング
ドメインエキスパートから、
* ～するとき
* もしそうなったら、～
* ～の場合は、通知してほしい
* ～が発生した時に
などのフレーズが出てきた場合は、ドメインイベントを使用するタイミングである。

## 何がうれしいの？
[実践DDD本 第8章「ドメインイベント」～出来事を記録して活用～ (1/3)：CodeZine（コードジン）](https://codezine.jp/article/detail/10392)のまとめを参考にしています。

* 結果整合性（結果として一貫性が保たれること）を用いたシステムの構築が容易となる。
> 結果整合性とは ひとことで言うならば、「更新はそのうち全体に反映される」です。
１つのファイルをアップロードすると順次分散用のコピーが始まります。これにより障害時にファイルが消える確率を最小化することができます。一方で、複数ユーザが同じファイルをアップロードや更新した場合はどうなるでしょうか。衝突（コンフリクト）しそうですよね。結果整合性では、最後に更新した処理が終わると、時間が経てば必ず全てのストレージに最新情報が反映されます。そのうち反映されるというのは、かなり割り切った使い方ですが、常に最新を表示する必要がないデータを扱う用途にはピッタリです。例えば、Twitterのつぶやきはそのうち反映されればいいですよね。
> [Amazon S3 の結果整合性と読み取り一貫性 ｜ Developers.IO](https://dev.classmethod.jp/cloud/amazon-s3-eventually-consistent-and-consistent-read/)より

* メインイベントを利用することで、密結合になりがちな他システムとの連携や、他の集約へのデータ反映を疎結合になる。
    * Obserberパターンを使用して、イベントドリブンに他システムと連携をするので疎結合にすることが可能。
* 複雑なバッチ処理からの解放
    * 従来のバッチ処理
        * 多くのシステムでは混雑していない夜間の時間帯に、日時のメンテナンス処理を行っているはずです。
        * この処理では、日中に発生した処理を特定して複雑で長いトランザクションを発行するというものが多いようです。
    * ドメインイベント
        * ドメインイベントを導入した場合、システム内のリスナがそのイベントを受け取るので『対象の特定』『起こったイベントの特定』が容易に行えます。
        * また、結果整合性を用いるのならば処理の実行を満遍なく分割することで日中に実行することも可能となる。
* 集約の制約からの解放
    * 集約の制約として「単一のトランザクションでは単一の集約の固まりだけを変更しなければいけない」という推奨ルールが存在しています。ドメインイベントを使用することでトランザクションの範囲を拡大することがかのうです。
