### ISSUE TITLE
9章 モジュール

### ISSUE THREAD

**Issue by shirosuke** [hiromoon/ReadingDDD#12]
## モジュール
* クラスの名前空間を設定する概念
  * Java: Package
  * C#: NameSpace
  * Ruby: Module

## 9.1
* ドメインオブジェクトを表現するクラス郡をまとめる「名前付きコンテナ」
* 別モジュールのクラスとの結合度を下げる目的
* エンティティ、値オブジェクト、サービス、イベントと同様の扱いとする
  * 繰り返し修正しながら作り上げよう
* クラスの適切な置き場所を作ることが大切
* OSGiバンドルやJigsawなどの上位の概念で、使えるようにモジュールを疎結合に設計する

### モジュールを設計する際のルール(9.1章 表9-1 引用)

|モジュールの「べし」「べからず」|その理由|
|:---|:---|
|モジュールはモデリングの概念にフィットするように設計すべし|通常は、ひとつあるいいはごく少数の凝集した集約(10)ごとに一つのモジュールを用意する。|
|モジュールの名前は、ユビキタス言語に従うべし|これはDDDの基本目標のひとつでもあるが、モデリングする概念について考えていれば、ごく自然にそうなるだろう。|
|コンポーネントの型やモデル内で使っているパターンなどから、モジュール名を機械的に決めるべからず|たとえば、すべての集約をまとめたモジュールをひとつ、同じくすべてのサービス(7)をまとめたモジュールをひとつ、そしてすべてのファクトリ(11)をまとめたモジュールをひとつ、などという分け方をしても、まったく無意味だ。そんなことをすればDDDのモジュールの本質を失ってしまうし、豊かなモデリングに制約を課すことになる。ドメインそのものについて考えるのではなく、目の前の問題の解決手段としてのコンポーネントやパターンにだけ目を向けるようになってしまう。|
|モジュールは、疎結合になるよう設計すべし|個々のモジュールが他のモジュールに依存しないようにしておけば、クラスを疎結合にするのと同じメリットが得られる。概念のモデリング結果を保守したりリファクトリングしたりするのが楽になるし、OSGiやJigsawのような上位レベルでのモジュール化機能も使えるようになる。|
|対等なモジュールどうしの結合が必要になる場合は、循環依存にならないようにすべし(対等なモジュールとは、同じ「レベル」にある、つまり、同程度の重要度だったり、同じ方向を向いて作られていたりするモジュールを指す)|モジュールどうしを完全に独立させることはめったにないし、あまり現実的ではない。結局のところ、同じドメインモデルになるという時点dジェ、何らかの関連があるわけだ。しかし、対等なモジュール間の依存関係を単一方向のみにする(たとえば、productはteamに依存するが、teamはproductに依存しないなどとする)よう心がければ、コンポーネント間の結合を減らせる。|
|親子関係のモジュールの結合の場合は、ルールを多少緩和すべし(親モジュールは上位レベルにあるモジュール、小モジュールは下位レベルにあるモジュールを指す)|親子関係にあるモジュール間の依存関係を排除するのは、極めて難しい。それでも、可能な限り、親子間の循環依存を避けるべきだ。しかし、どうしても無理なら、循環依存が発生することもやむを得ない(たとえば、親が子を作り、子はその親の識別子を参照する必要がある場合など)。|
|モジュールをモデルの静的な概念とせず、モジュールが取りまとめるオブジェクト郡に合わせて変えるべし|モデルの概念に柔軟性があって、さまざまな状態や振る舞いや名前に対応できるものなら、それらをまとめるモジュールもまた、同じ特徴を持たせるべきだ。必須ではないが、もしうまくマッチしていない名前を見かけたら、リファクタリングしよう。つらい作業だろうが、ひどい名前のモジュールをそのまま放置しておけば、後でもっとつらい思いをすることになる。|

## 9.2
* JavaやC#ではモジュール名を階層構造で表現している
* インターネットのドメインをトップレベル名に使うことで、名前空間の衝突を避ける

## 9.3
* モジュール名は境界づけられたコンテキストの名前にあわせるとよい
* エンドユーザ向けのサービス名などは変更しうるので、内部向けのプロダクト名で構わない

**Comment by shirosuke** [comment]
## 9.4 アジャイルプロジェクト管理コンテキストのモジュール
* アジャイルプロジェクト管理コンテキストを利用した具体例。
* ドメインモデルの数が多くなることを見据えて、細かくモジュールを分けている。
  * エンティティ、バリューオブジェクト、ドメインイベント等のクラスをフラットに配置するとわかりにくい。
  * com.saasovation.agilepm.domain.model.product　下にユビギタス言語に従った用語で、細かくモジュール構成を分けている。
* 組織的な強度（業務に従ったモデリングをすること？）と疎結合はトレードオフになる。
  * 前者を取るパターン：きちんと業務に沿ったモデリングができるが、依存（場合によっては双方向依存も）が発生する。
  * 後者を取るパターン：汎用型の型を採用することによってモジュール間の依存は減らせるが、個々の型を識別できないので、バグは発生するリスクを上げてしまう。

## 9.5　他のレイヤにおけるモジュール
* ドメインモデル以外のモジュールを考える時の具体例。
* サブモジュール分割するタイミングは、あくまでそれが役に立つ時だけ。

## 9.6 境界づけられたコンテキストの前にモジュールを検討する
* 概念的な境界（境界づけられたコンテキスト）を定める前に、まずモジュールを検討する。
* モジュールは、凝集したドメインオブジェクトをモジュール化したり、凝集していないドメインオブジェクトを切り分けたりする時に使う。

## 9.7 まとめ
本書を参照。

**Comment by shirosuke** [comment]
親切な人がサンプルコードのモジュール名を記載してくれてた。
https://qiita.com/suin/items/8ff2d3b99af795cd03f2

**Comment by Shusaku-Sahashi** [comment]
9.3章の詳細なまとめ書いといた。

## モジュールの命名（ドメインモデルより上層は少しはしおってる）
### コンテキスト名
com.saasovation. ____ <-この部分に各コンテキスト名が入る。

* com:会社毎のトップドメイン
* saasovation: プロダクト名

コンテキスト名の層を作成するときの注意点以下の通り。
* コンテキスト名と１語１句そろえる必要は必ずしもない。
* 顧客向けのブランド名を使うと、ブランド名称が変更された時に問題となる。
    * これに関しては、開発名称を使用すればいい？

⇒結論：とりあえず、コンテキストを開発Tが識別できて、複雑な名前でなければなんでも良い。

### モジュール
com.saasovation.agliepm.module

次の層として`module`の追加を行う。`module`はインターフェイス/クラスを含まず、モジュールの純粋なコンテナとして働く。

### モデル
com.sassovation.agliepm.module.model

再利用可能なインターフェイス、抽象クラスを格納する。

### サービス
com.sassovation.agiliepm.module.service

サービスを格納するために、`service`モジュールを作成しても良い。しかし、サービスを作りすぎて振る舞いを過剰に抽出すると、
ドメイン貧血症になるので注意。
また、`module`と`service`をひとまとめにして`module`上に格納することも可能だが、後から`service`モジュールを作成したいとなったときに
後悔をするので作成しておいた方が無難。
