### ISSUE TITLE
10章 集約

### ISSUE THREAD

**Issue by shirosuke** [hiromoon/ReadingDDD#13]
* エンティティや値オブジェクトを１つの集約にまとめる
* 集約という概念はDDDの中で最も理解されていないパターンの１つ

## 10.1
1. 巨大な集約
  - 集約が大きすぎると本来不要な制約が増えてしまう
  - 不適切な削除を防ぐためのトランザクションの制御が複雑になる
  - パフォーマンスやスケーラビリティにも問題がある
2. 複数の集約
  - 巨大な集約をいくつかの集約へ分割する
  - トップレベルの集約をファクトリとして機能させる
    + 集約のインスタンスを外へ出すことでライフサイクルの管理を持たせない
    + __トランザクションを外部に追い出した__

## 10.2
* 不変条件: 常に整合性を保っている必要のあるビジネスルール
  + トランザクション整合性 ← 不変条件をについて議論する時の整合性
    - 即時かつアトミックに整合性を保つ
  + 対義 => 結果整合性
* 集約はトランザクション整合性を担保するクラス
* 「１つのトランザクションではひとつの集約のインスタンスしか変更できない」を目指すべき
  - UIからのリクエストは１つの集約のインスタンスに対する単一のコマンドにする

### 巨大な集約のデメリット
  - 集約の全体をメモリ上に載せる必要がある
  - メモリ展開のパフォーマンスに影響する
  - スケールさせづらい
  - 遅延読み込みができるなら話は別だが。。。

### 小さな集約
* ルートエンティティとその他最小限の属性
* 必要最小限に抑えるのが正解
  - 必要な要素 => 他の要素と整合性を保つ必要があるモノ
* 多くの集約にはルートエンティティ以外のエンティティが不要
* トランザクションの範囲が狭くなるので、他の処理との衝突によるコミットの失敗が少なくなる

## 10.4
* ある集約が別の集約のルートへの参照を保持しても良い
  - 同一の集約になるという意味ではない
* ただし、「単一のトランザクションでは単一の集約の変更しか許さないの」は変わらない
  - 巨大な集約につながりがちだが、結果整合性で整合性を保持する方法に切り替えるべき
* 識別子への参照を使う
  - 巨大な集約にせずに集約への参照を持たせる
  - オブジェクトそのものへの参照を保持しないようにするのが良い
  - 利用するまで対象のオブジェクト(集約)の読み込みを遅延させることができる
  - オブジェクトのサイズが小さくなり、読み込みに有利・メモリの使用量が少なくなる
  - __切り離されたドメインモデル__
    + 集約内からリポジトリを使って他のモデルの中を辿ることもできる
  - 【IDDDおすすめ】リポジトリorドメインサービスを使って、集約の振る舞いを実行する前に依存オブジェクトを検索する
    + 事前にオブジェクトをロードしておく(?)
    + アプリケーションサービスに依存関係を解決させる
    + パフォーマンスに問題がある場合には、 __シータ結合__ やCQRSの利用を検討する

## 10.5
* 単一のリクエストで複数の集約を変更する必要がある場合
  - 結果整合性を受け入れる
  - すべての集約のインスタンスの整合性を完全に維持するのは不可能
* データの整合性を保つのは誰の役割なのか?
  - ユーザの役割: => トランザクション整合性
  - 別のユーザ(orシステム): => 結果整合性

## 10.6
ルールの例外ケース
1. ユーザインタフェースの利便性
  * 例: 複数のバックログアイテムを一括作成する場合
  * 集約のインスタンスそれぞれが不変条件を管理しているので実害はおそらくない。
2. 技術的な仕組みの欠如
  * 結果整合性のためには、境界を越えた処理ができなければならない。
    - メッセージング、タイマー、バックグラウンドスレッドetc...
    - これらがすべて使えないプロジェクトもある(まじかよ...)
  * 巨大な集約にしないために複数の集約を単一トランザクションで変更する
  * ユーザと集約の親和性が確保されていればルール違反してもおｋ
    - 不変条件やトランザクションの衝突を回避できるだろうからだ(なぜだ。。。?)
3. グローバルなトランザクション
  * レガシー技術や企業内のポリシーの影響
  * グローバルな二相コミット方式のトランザクションを使うことを強いられる場合もある
  * 複数の集約のインスタンスを一度に変更しないといけないとは限らないことに注意
    - できるだけ回避することでトランザクションの衝突を避けることができる
4. クエリのパフォーマンス
  * リポジトリの問い合わせのパフォーマンスを向上させたい場合
    - 直接他の集約への参照を持つことで改善することがある
   * 集約のサイズの肥大化や全体的なパフォーマンスの低下とのトレードオフになる点に注意

## 10.7
* 依存関係なのか参照なのかを見極めることで集約を小さく分割できる
* 一般的なシナリオを用意すること
  - 最大で使われるオブジェクトの数は？
  - 並行処理が衝突してしまうことはないか?
  - etc...
* UIの不整合は見逃す
  - 結果整合性を用いると一時的にユーザへの表示とデータの状態が一致しない
  - 更新に時間がかかる旨を画面に表示することで回避する
  - ポーリングやComet、Webscoketなどを使って反映した瞬間に表示を切り替えることもできる(コストと相談)

## 10.8 
省略

**Comment by Shusaku-Sahashi** [comment]
ここの生地がよく纏まっている。
https://qiita.com/tassi-yuzukko/items/9729ff58e0a59ede1640
