### ISSUE TITLE
12章 「リポジトリ」

### ISSUE THREAD

**Issue by hiromoon** [hiromoon/ReadingDDD#15]
## リポジトリ
* 何かを保管する場所
  - 取り出したときに保管したものと同じ状態で戻ってくる
* 集約のインスタンスを対応したリポジトリに保管する
  - 使うときにはリポジトリを使って同じインスタンスを取り出す
* インスタンスを変更した場合にはその状態が永続化される
* リポジトリからインスタンスを削除した場合には、以降そのインスタンスを取得できない
* 一般的にはリポジトリと集約型は1:1対応
  - 集約型が階層構造になっている場合には、1:N対応になることもある

## 12.1
* コレクション志向のリポジトリは、永続化メカニズムを隠蔽する
* HashSetの特徴を兼ね備えた永続データストアが実装目標
* 永続化メカニズムは、管理するオブジェクトの変更履歴を追跡する仕組みが必要
  1. 暗黙のコピーオンリード
    - データストアからの読み取り時にオブジェクトのコピーを作る
    - 保存の際には作成したコピーと渡されてオブジェクトを比較する
    - 比較によって変更があることがわかった場合データストアに書き出す
  2. 暗黙のコピーオンライト
    - オブジェクトの管理をプロキシ経由で行う
    - 薄いプロキシを作成しクライアントへ渡す
    - クライアントは無意識的にプロキシオブジェクトの振る舞いを実行する
    - プロキシは最初の実行命令を受け取ったときにオブジェクトのコピーを作る
    - プロキシはオブジェクトに変更があった場合にはマークを付ける
    - 永続化メカニズムは変更マーク付きのオブジェクトを探し出しデータストアへ書き出す
* 暗黙的な管理はトレードオフ
  - Hibernateの機能で実現可能
  - ただし、メモリや速度の面でオーバヘッドになりうる
  - 利用にあたってはドメインの条件を見て判断すること
* TopLink(ORM)は明示的なコピービフォーライト
  - 明示的 => クライアントから変更を指示する必要がある
  - 変更の通知を受け取ったらオブジェクトをクローンして変更に備える
  - 必要になったときにしかメモリを消費しない

## 12.2
* 永続化メカニズムにオブジェクトの変更を検出・追跡する機能がない場合にはコレクション方式が使えない
  - NoSQLやインメモリのデータファブリックを使う場合
  - 新しい集約のインスタンスを作ったり、変更したりするたびにsave()を呼ぶ必要がある
* コレクション指向 => 永続指向への変更もありえる
* リポジトリパターン
  - デメリット: ORMのせいで必要な場面でsave()が使えなくなる可能性がある
  - メリット: 永続メカニズムを簡単に入れ替えることができるようになる

## 12.3
* リポジトリのインタフェースに用意しておくと有用なものがある
  - size(): コレクション内のインスタンス数を返す
    + 非機能要件を満たすために、データストア側に処理を寄せることもおおい
    + ストアドプロシージャなどを使う
* 集約の一部のみを取得する
  - ルートから辿れる場合のみOK　
    - 集約の契約に違反してしまう
  - 利便性のためではなく、パフォーマンスに問題がある場合のみ
  - ビューをレンダリングする場合に、複数の集約を扱う場合
    - プログラム内で組み合わせを扱いたくない
      + ユースケースに最適化されたクエリを使うのがよい
* 最適化されたクエリを多用するような状況になった場合には注意
  - 境界の判断を見誤っている可能性が高い
  - 「集約の設計ミスを覆い隠すリポジトリ」
  - 集約の境界は特に間違っていないと思える場合にはCQRSを使う

## 12.4
* モデルにトランザクションへの関心をもたせるべきではない
* 一般的にはアプリケーションレイヤを使う
* ユースケース単位でファサードを作ることが多い
  - ファサード: 粒度の粗いビジネスロジック
  - ユースケースごとに一つのメソッドになる
* ファサードはUIレイヤから実行され、トランザクションを開始する
* トランザクションの管理は、明示的でも宣言的でも構わない
* ドメインモデルとトランザクションの組み合わせは乱用してはいけない
  - それよりも集約の設計時に、整合性の境界を正しく定義するべき
 
## 12.5
* 少数の集約型がドメインに特化した共通のスーパークラスを継承して作られる例
  - ポリモーフィズムを持つような型どうしを、階層構造にまとめる例
  - 単一のリポジトリを使ってすべての型のインスタンスの格納や取り出しを行う。
  - クライアントから見たときにすべての型が交換可能([リスコフの置換原則](https://ja.wikipedia.org/wiki/%E3%83%AA%E3%82%B9%E3%82%B3%E3%83%95%E3%81%AE%E7%BD%AE%E6%8F%9B%E5%8E%9F%E5%89%87))
* 共通の基底クラス(SeviceProvider)を用意する
  - 実装はサービスごとに分けている(WarbleServiceProvider, WonkleServiceProvider)
  - ファインダーメソッドはServiceProviderのインスタンスを返す
* 型ごとに違う操作をしたい場合
  - 型情報を区別するための識別子を埋め込む
    - クライアントと型が密結合するのであまり良くない
  - 暗黙のServiceDescription型とscheduleService()を使えばよい
  - 識別子ではなく、集約のプロパティとして用意する
    + 「値オブジェクト」の標準型に関する議論を参照
  - 型情報をクライアントから隠蔽するように設計する
  - 単一のServiceProviderRepositoryを持つ
    - 複数の型を単一のリポジトリに格納し、共通の振る舞いを使えるようにしたいという要求に対応する
  - ロールベースのインタフェースを使っても良い
    - SchedulableServiceインタフェースを定義して、それを実装した集約型を複数用意する。
      + 「エンティティ」でのロールや責務に関する議論を参照

## 12.6
* DataAccessObject(DAO)
  - DBのテーブルに対してCRUDインタフェースを提供するもの
    + Fowlerはドメインモデルと組み合わせて使うDAO風の機能を紹介している
      - テーブルモジュール
      - テーブルデータゲートウェイ
      - アクティブレコード
    + これらのパターンはトランザクションスクリプトのアプリで使われることが多い
  - DAOはテーブルに対するラッパーとして用いられる傾向がある
  - 必要以上に細かい操作ができてしまうのでドメインモデルと組み合わせないほうが良い
* リポジトリ、データマッパー
  - オブジェクトとの親和性が高い
  - ドメインモデルと組み合わせて使われることが多い
* ストアドプロシージャ、エントリプロセッサ(データグリッド)
  - 非機能要件を満たすために使う場合もある
  - 非機能要件が要求されていないなら使うべきではない
    - ドメインモデルの目的を達成できているなら使うのはよい
    - ストアドプロシージャの言語をモデリングチームに知られていないことが多い
    - 実装がモデリングチームに見逃されてしまうことが怖いため、乱用は避けたほうが良い
* データアクセス指向よりコレクション指向
  - データ操作よりもドメインモデルに集中するべき

## 12.7
1. リポジトリ自体が正しく動くかを確かめるテスト
  - プロダクションコードと同レベルの実装を使う必要がある
  - プロダクションコードが正しく動くかわからないから
2. リポジトリを使う側のコードが操作を正しく行えるかを確かめるテスト
  - プロダクションレベルの実装でも、インメモリのリポジトリを代わりに使ってもよい

**Comment by shirosuke** [comment]
今週の予習分がもうまとめられてたので、IDDDサンプル見ながらまとめ＆考察してみた。

### 12.5
* 集約型の階層を持っているのは、com.saasovation.agilepm.domain.model.team.Member 
  * ProductOwnerとTeamMemberのクラスがMemberの派生クラス
  * サンプルだとそれぞれRepositoryを作るパターンを採用している。
    * まぁアジャイルpmのコンテキストで登場する人物って、そんないないし。。（後定義するならScrumMasterくらい？）共通処理を持つリポジトリを定義するまでもないと判断したのかな。

### 12.6
* サンプルの中にXXXDaoというクラスは登場しなかった。データアクセスの部品はRepositoryパターンを採用し、コレクション指向で実現している。
* com.saasovation.agilepm.application.product.ProductApplicationService　とか見ると、Repositoryを駆使してガシガシ実装している感じ。
* 実体験だけど、ユースケース的に複数のコンテキストを横断して検索、かつテーブルをjoinして〜みたいなものが多くなってくると、Repositoryだけでやるとしんどいかった。
  * そーいう要求が見込まれるなら、あらかじめCQRS採用していコマンド要件とクエリ要件を分けてモデリングしておくと良いかも。
    * コマンド・・・コレクション指向。データアクセスにはRepositoryを使う。
    * クエリ・・・データアクセス指向。データアクセスにはDAOを使う。
    * 分けて成功した事例
      * https://www.slideshare.net/koichiromatsuoka/ddd-x-cqrs-orm

### 12.7
* サンプルだと、LevelDBの実装クラスしかなかった。よってテストはLevelDBものしかないので、動かすならミドルウェアのセットアップは完了させておく必要がある。
* 実プロジェクトで開発進めていく際にDBの選定やら構造やらセットアップやらで時間がかかって開発に支障が出そうなら、インメモリのRepositoryを作っておいた方が良いと思う。
  * Inmemoryとはいえテストもかけるし。12.7の2観点の内の後者のやつはこれで満たせる。
