### ISSUE TITLE
2章「ドメイン、サブドメイン、境界づけられたコンテキスト」

### ISSUE THREAD

**Issue by hiromoon** [hiromoon/ReadingDDD#2]
* ドメイン
  - 業務で扱う領域
* サブドメイン
  - ドメインを成立させるために分割した細かな業務領域
  - 明確に業務に紐付けられないが必要なドメインは汎用ドメインに割当てられる
    + 文中では認証・アクセスコンテキストが取り上げられている
* 境界づけられたコンテキスト
  - 業務領域の分割によってユビキタス言語が統一された領域(Contextの文字通り文脈が統一された地域)
  - サブドメインと1対1対応していることが望ましい

<編集中>

**Comment by hiromoon** [comment]
ドメインの概念がふんわり理解できた。
業務の領域によって責務の分割をキチンとすることと、それをユビキタス言語を基準に行うことで可読性の高いソースコードを記述する狙いがあると理解した。
自分が関わっていることもあるが、積極的にマイクロサービスに分割して行こうという考え方な気がしている。
一方で、その分割時にデータ自体の粒度の扱いかたをどうするのかが気になった。
ソースコード起点での考え方が多い気もするが、ドメインモデルを扱う上でデータの整合性も無視できない課題だと思うので、今後どう解決していくのか興味深いと感じた。

**Comment by Shusaku-Sahashi** [comment]
境界づけられたコンテキスト、ドメインの概念が分かった。

・境界づけられたコンテキスト
システムやアプリケーションなど実態をもつものを指す。コンテキスト毎にユビキタス言語を定める。そのため、コンテキストを跨いで状態やモデルを取得するときは、このユビキタス言語のギャップが生じる。これについては３章以降？
（コンテキスト毎にユビキタス言語を分ける利点は以下を参照
http://little-hands.hatenablog.com/entry/2017/11/28/bouded-context-concept）

・ドメイン
ユーザの業務やノウハウなど、概念的なことを指す。会社や顧客側からみれば、これらドメインをいかに組み合わせてサービスを提供するかを考える。
ただ、概念的なものなので、１つのドメインに複数のコンテキスト（アプリ）があることもありうる。
その場合、１つの動作を行い場合に複数のコンテキスト（アプリ）に問い合わせなければいけないく、凝集度の問題が出てくる。基本的にはこれらドメインを組み合わせることで複雑な業務を行うことを目指す。

究極的な理想は、１コンテキスト１ドメインにすること。こうすれば、業務に対して１つのコンテキストにアクセスするだけで済むから。

〇疑問点
・境界付けられたコンテキストの大きさは、ユビキタス言語の全容を表現できるだけが望ましいと書いてあったが、ユビキタス言語->境界付けられたコンテキスの順で定めればいいのか？

**Comment by shirosuke** [comment]
## 学習点
* 自分のチームが扱う業務領域（ドメイン）について、1つのものとして扱うのではなく、関心事によって複数のサブドメインに分割し、その中で最も事業戦略的に有効な箇所をコアドメインとして設定する。
  * 汎用サブドメインは、自身の事業と本質的には関係ない箇所なので、外部サービスやパッケージ等を解決手段として利用することも検討できる。

## 疑問点
* ホワイトボードの時間の活用方法
  * 活用方法がいまいちピンと来なかった。
