### ISSUE TITLE
3章 「コンテキストマップ」

### ISSUE THREAD

**Issue by hiromoon** [hiromoon/ReadingDDD#3]
### コンテキストマップ
> コンテキストマップ は、 現存する地形をとらえるものだ。 まずマッピングすべきは現状であり、こう あってほしいという将来の姿ではない。
ヴァーン・ヴァーノン. 実践ドメイン駆動設計 (Kindle の位置No.2724-2725). 

### コンテキストの関係

2つの境界づけられたコンテキストの間のパターン
コンテキストの現状に合わせて下記のパターンのなかから対応方法や方針を決定すると良い
* パートナーシップ
  - 2つのコンテキストを担当するチームが運命共同体の場合
  - 協力的な関係を築く必要がある
  - 相互依存する機能はお互いのリリースに間に合うようにがんばる
* 共有カーネル
  - 一部のモデルやそれに関連するコードを共有する
  - 境界を明示的に定めて、2チームが共有することに同意したモデルを用いる
  - 変更時に勝手に変更できない(チーム間の相談が必須)
  - 変更が気軽にできなくなるデメリットがあるので、できる限り小さくまとめる
  - ユビキタス言語に合わせてカーネルのモデルを維持する
* 顧客/供給者の開発
  - 2チーム間に上流/下流の関係がある場合
  - 上流の成否が下流チームの成否に左右される
  - 上流は下流チームの成功を優先して作業する
* 順応者
  - 2チーム間に上流/下流があるが、上流が下流の要求に応える気がない場合
  - 下流はどうすることもできない
  - 上流に与えられたに与えられたモデルで我慢することになる
* 腐敗防止層
  - 変換層
  - 上述のようなパターンが取り除けなかった場合に設ける
  - 内部的には2つのコンテキストの中間に位置し、双方向に変換を行う
* 公開ホストサービス
  - プロトコルをサブシステムに公開すること
  - 共通した新しい統合要件に対する際には、このプロトコルを拡張する
  - 特定のコンテキストに特有の拡張が必要な場合には、1回限りの変換サービスを使用してプロトコルを拡張する(?)
* 公表された言語
  - 2つの境界づけられたコンテキストのモデル同士を変換するために用いる共通言語
  - 明確にドキュメント化された共有言語を使用する(!!?)
  - 公開されたホストサービスと組み合わされて使われることが多い
* 別々の道
  - 要件定義は容赦なく行わなければならない
  - 同一のコンテキストにあることが必須でないなら積極的に切り離す
  - 切り離すことでスコープを小さくしシンプルにする
* 巨大な泥団子
  - 既存のシステムを分割しようがない場合。。。
  - 諦めて一つの大きなドメインモデルとして扱う
  - きれいにモデリングしてやろうなどと考えてはいけない

**Comment by hiromoon** [comment]
コンテキストマップの概要と出来上がったコンテキスト間の扱い方について理解した。
コンテキスト間の関係について、いくつかのパターンについて見たが、基本的にはコンテキストごとに分離して、間にインタフェースやトランスレータを挟むことで強依存にせずに扱うことを提案していると理解している。
コンテキストマップの書き方がいまいちピンと来なかったので実際に書いてみることが大事だと感じた

**Comment by Shusaku-Sahashi** [comment]
以下サイトに図ありで載っていたので、こちらの方が感覚的に理解が進みそう。
https://codezine.jp/article/detail/9837?p=2

**Comment by shirosuke** [comment]
## まとめ

- プロジェクトの現状について、境界づけられたコンテキスト群それぞれに関連がマッピングされたものがコンテキストマップ
- コンテキストマップを作成する目的は、解決領域の全貌を俯瞰するため。
  - 外部のプロジェクトが提供するもの（外部システム）等も考慮してマッピングを書くと、早い段階でプロジェクトのリスクを検知できそう。
    - まったく融通が聞かないシステム⇨順応者、もしくは巨大な泥団子の統合パターンとして、そのコンテキストを扱う。
    - 調整可なシステム ⇨ 顧客・供給者の開発の統合パターンにもっていけるかも。
  - コンテキストマップは全員が容易にアクセスできる場所に置くこと。
    - 作成の指針は、議論の叩き台になる程度のレベルの簡易さで良い。
    - 細かく書きすぎるとメンテが大変で、参照されないドキュメントになってしまう。
  - コンテキスト間のモデルの変換は、公表された言語（PL）にて行う。　
  - 統合のパターンをどのように実装するかについては13章を参照する。
    - 3章で言及されていた実装方式は、REST、メッセージング。
