### ISSUE TITLE
5 章 「エンティティ」

### ISSUE THREAD

**Issue by hiromoon** [hiromoon/ReadingDDD#6]
* オブジェクトを一意に識別する必要がある場合に用いる
* オブジェクトとして長期で変更するようなもの

## 識別子
一意な識別のつくりかたも色々ある
1. アプリケーションが作って面倒を見る
2. アプリケーションフレームワークに任せる
3. RDBに任せる
4. ユーザに入力させる

4.選択した場合に、変更や保守のコストが高くつかないか検討する必要がある。

複数に分散した環境で一意な識別子をつけたい場合には、UUIDやGUIDが使われる事が多い。

### 識別子の生成タイミング
* 早期生成: オブジェクト生成のタイミングで識別子も生成する
* 遅延生成: オブジェクトを永続化するタイミングで識別子を生成する

**Comment by Shusaku-Sahashi** [comment]
## イメージできなかった部分
>識別子生成のタイミングが問題になるのだろう?　たとえば、外向きのイベントを購読しているクライアントがあると仮定しよう。このイベントは、新しいProduct のインスタンスが作成されたときに発生するものだ。クライアントは、受け取ったイベントをイベントストア(8) に保存する。最終的に、保存されたイベントは、境界づけられたコンテキストの外部にいるサブスクライバたちに向けた通知として発行される。図5‒3 の手法を使うと、ドメインイベントを受け取った時点ではまだ、クライアントは新たなProductをProductRepository に追加できないという状態になる。したがって、このドメインイベントには、新しいProductの正しい識別子が含まれなくなってしまう。ドメインイベントを正しく初期化するには、識別子の生成が早期に完了していなければいけない。図5‒4  は、その場合の流れを示したものだ。
(「識別子生成のタイミング」より)

## 用語の整理
* イベントストア
    * イベントが発生した順に管理するもの。キューのようなもの。（たぶん）
    * 今回は受け取ったイベントを再利用している？（疑問点）
    　（受け取ったイベントをイベントストア(8) に保存する。最終的に、保存されたイベントは、
     　　境界づけられたコンテキストの外部にいるサブスクライバたちに向けた通知として発行される。）

* サブスクライバ
    * Publisher, Subcriberの関係。ほとんどObserverパターンと考えても良い。
* ProductRepository
    * 永続化を実行する。

## 解釈
まず「イベントは、新しいProduct のインスタンスが作成されたときに発生する」という前提。
その場合、遅延生成と早期生成では動きに以下の違いが生まれる。
* 遅延生成
    * 「クライアントは新たなProductをProductRepository に追加」時に識別子が生成される。
    * 「Subcriberに通知するドメインイベント送信タイミング」 = 「イベントは、新しいProduct のインスタンスが作成されたときに発生するタイミング」でないといけないため、整合性が合わない。
* 早期生成
    * ProductRepositoryに関係なく、識別子の生成が可能。
    * Productインスタンス生成時には識別子が確定しているので、正しい識別子を含んだイベントをSubcriberに通知することも可能。
